data:
  name: jdd_boost
model:
  class: whisper_frontend_lcnn
  id: whisper_mfcc_lcnn
  parameters:
    freeze_encoder: true
    frontend_algorithm:
    - mfcc
    input_channels: 2
training:
  batch_size: 16
  init_weights: ''
  max_epochs: 30
  optimzer:
    lr: 0.0001
    weight_decay: 0.0001
