data:
  name: jdd_boost_context
model:
  class: mesonet_context
  id: mfcc_mesonet_context
  parameters:
    context: ct
    fc1_dim: 1024
    frontend_algorithm:
    - mfcc
    input_channels: 1
    embedding_dim: 100
training:
  batch_size: 16
  init_weights: ''
  max_epochs: 30
  optimzer:
    lr: 0.0001
    weight_decay: 0.0001
